import { createSlice, PayloadAction } from '@reduxjs/toolkit';

// Define the interface for the TODO object
interface Todo {
  id: number;
  text: string;
  completed: boolean;
}

// Sample initial state with some TODOs
const initialState: Todo[] = [
  { id: 1, text: 'Learn React', completed: false },
  { id: 2, text: 'Build a TODO app', completed: true },
];

// Create a slice for the TODOs
const todosSlice = createSlice({
  name: 'todos',
  initialState,
  reducers: {
    addTodo: (state, action: PayloadAction<Todo>) => {
      state.push(action.payload);
    },
    updateTodo: (state, action: PayloadAction<Todo>) => {
      const { id, text, completed } = action.payload;
      const todoToUpdate = state.find((todo) => todo.id === id);
      if (todoToUpdate) {
        todoToUpdate.text = text;
        todoToUpdate.completed = completed;
      }
    },
    deleteTodo: (state, action: PayloadAction<number>) => {
      return state.filter((todo) => todo.id !== action.payload);
    },
  },
});

// Export the actions generated by createSlice
export const { addTodo, updateTodo, deleteTodo } = todosSlice.actions;

// Export the reducer to be used in the Redux store
export default todosSlice.reducer;
